project_id = "ofgqaywlumvfjtsbhfhg"

[functions.create-user-with-role]
verify_jwt = true

[functions.create-manager]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.relatorio-insights]
verify_jwt = true

[functions.ana-executiva]
verify_jwt = true

[functions.ana-insights]
verify_jwt = true

[functions.ana-scheduler]
verify_jwt = false

[functions.ana-alerts]
verify_jwt = false

[functions.whatsapp-dispatch]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false
